src/Bazza/Controllers/AdminSalesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Adliance.AspNetCore.Buddy.Pdf.V2;
using Adliance.AspNetCore.Buddy.Template.Razor;
using Bazza.Models.Database;
using Bazza.ViewModels.AdminSales;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bazza.Controllers;

public class AdminSalesController : Controller
{
    [Authorize(Roles = Roles.CanManageSales), HttpGet("/admin/sales")]
    public async Task<IActionResult> Sales([FromServices] SalesViewModelFactory factory)
    {
        return View(await factory.Build());
    }

    [Authorize(Roles = Roles.CanManageSales), HttpGet("/admin/sales/statistics")]
    public async Task<IActionResult> SalesStatistics([FromServices] SalesStatisticsViewModelFactory factory)
    {
        return View(await factory.Build());
    }

    [Authorize(Roles = Roles.CanManageSales), HttpPost("/admin/sale/create")]
    public async Task<IActionResult> CreateSale([FromServices] Db db)
    {
        var existingSalesIds = await db.Sales.Select(x => x.Id).ToListAsync();
        var newSalesId = 1;
        while (existingSalesIds.Contains(newSalesId)) newSalesId++;

        await db.Sales.AddAsync(new Sale
        {
            CreatedUtc = DateTime.UtcNow,
            Id = newSalesId,
            Username = User.Identity?.Name
        });
        await db.SaveChangesAsync();

        return RedirectToAction(nameof(Sale), new { id = newSalesId });
    }

    [Authorize(Roles = Roles.CanManageSales), HttpGet("/admin/sale/{id}")]
    public async Task<IActionResult> Sale([FromServices] SaleViewModelFactory factory, int id)
    {
        return View(await factory.Build(id));
    }

    [Authorize(Roles = Roles.CanManageSales), HttpGet("/admin/sale/{id}/pdf")]
    public async Task<IActionResult> Pdf([FromServices] ITemplater templater, [FromServices] IPdfer pdfer, [FromServices] SaleViewModelFactory factory, int id)
    {
        var viewModel = await factory.Build(id);
        var html = await templater.Render("Pdf", "Sale", viewModel);
        var pdf = await pdfer.HtmlToPdf(html, new PdfOptions());
        return File(pdf, "application/pdf", $"Verkauf {viewModel.Id}.pdf");
    }

    [Authorize(Roles = Roles.CanManageSales), HttpGet("/admin/sale/delete/{id}")]
    public async Task<IActionResult> DeleteSale([FromServices] DeleteSaleViewModelFactory factory, int id)
    {
        return View(await factory.Build(id));
    }

    [Authorize(Roles = Roles.CanManageSales), HttpPost("/admin/sale/delete/{id}")]
    public async Task<IActionResult> DeleteSale([FromServices] DeleteSaleViewModelFactory factory, DeleteSaleViewModel viewModel)
    {
        await factory.UpdateDatabase(viewModel);
        return RedirectToAction(nameof(Sales));
    }

    [Authorize(Roles = Roles.CanManageSales), HttpPost("/admin/sale/{id}/article")]
    public async Task<IActionResult> AddArticle([FromServices] SaleViewModelFactory factory, [FromServices] Db db, int id, string article)
    {
        ParseArticle(article, out var personId, out var articleId);
        if (personId <= 0 || articleId <= 0)
        {
            var viewModel = await factory.Build(id);
            viewModel.DisplayInvalidError = true;
            return View(nameof(Sale), viewModel);
        }

        try
        {
            var articleInDb = await db.Articles.SingleOrDefaultAsync(x => x.PersonId == personId && x.ArticleId == articleId) ?? throw new EntityNotFoundException();
            if (articleInDb.BlockedUtc.HasValue)
            {
                var viewModel = await factory.Build(id);
                viewModel.DisplayLockedError = true;
                return View(nameof(Sale), viewModel);
            }

            if (articleInDb.SaleId.HasValue || articleInDb.SaleUtc.HasValue)
            {
                var viewModel = await factory.Build(id);
                viewModel.DisplayAlreadySoldError = true;
                return View(nameof(Sale), viewModel);
            }

            var sale = await db.Sales.SingleOrDefaultAsync(x => x.Id == id) ?? throw new EntityNotFoundException();
            articleInDb.SaleId = sale.Id;
            articleInDb.SaleUsername = User.Identity?.Name;
            articleInDb.SaleUtc = DateTime.UtcNow;
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Sale), new { id = sale.Id });
        }
        catch (EntityNotFoundException)
        {
            var viewModel = await factory.Build(id);
            viewModel.DisplayInvalidError = true;
            return View(nameof(Sale), viewModel);
        }
    }

    [Authorize(Roles = Roles.CanManageSales), HttpPost("/admin/sale/{id}/article/{article}")]
    public async Task<IActionResult> RemoveArticle([FromServices] Db db, int id, string article)
    {
        ParseArticle(article, out var personId, out var articleId);
        if (personId <= 0 || articleId <= 0) RedirectToAction(nameof(Sale), new { id });
        var articleInDb = await db.Articles.SingleOrDefaultAsync(x => x.PersonId == personId && x.ArticleId == articleId) ?? throw new EntityNotFoundException();

        var sale = await db.Sales.SingleOrDefaultAsync(x => x.Id == id) ?? throw new EntityNotFoundException();
        if (articleInDb.SaleId == sale.Id)
        {
            articleInDb.SaleId = null;
            articleInDb.SaleUsername = null;
            articleInDb.SaleUtc = null;
            await db.SaveChangesAsync();
        }

        return RedirectToAction(nameof(Sale), new { id = sale.Id });
    }

    [Authorize(Roles = Roles.CanManageSales), HttpGet("/admin/blocked")]
    public async Task<IActionResult> Blocked([FromServices] BlockedViewModelFactory factory)
    {
        return View(await factory.Build());
    }

    [Authorize(Roles = Roles.CanManageSales), HttpPost("/admin/blocked/article")]
    public async Task<IActionResult> AddBlocked([FromServices] BlockedViewModelFactory factory, [FromServices] Db db, string article)
    {
        ParseArticle(article, out var personId, out var articleId);
        if (personId <= 0 || articleId <= 0)
        {
            var viewModel = await factory.Build();
            viewModel.DisplayInvalidError = true;
            return View(nameof(Blocked), viewModel);
        }

        try
        {
            var articleInDb = await db.Articles.SingleOrDefaultAsync(x => x.PersonId == personId && x.ArticleId == articleId) ?? throw new EntityNotFoundException();
            if (articleInDb.SaleId.HasValue || articleInDb.BlockedUtc.HasValue)
            {
                var viewModel = await factory.Build();
                viewModel.DisplayAlreadySoldError = true;
                return View(nameof(Blocked), viewModel);
            }

            articleInDb.BlockedUsername = User.Identity?.Name;
            articleInDb.BlockedUtc = DateTime.UtcNow;
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Blocked));
        }
        catch (EntityNotFoundException)
        {
            var viewModel = await factory.Build();
            viewModel.DisplayInvalidError = true;
            return View(nameof(Blocked), viewModel);
        }
    }

    [Authorize(Roles = Roles.CanManageSales), HttpPost("/admin/blocked/article/{article}")]
    public async Task<IActionResult> RemoveBlocked([FromServices] Db db, string article)
    {
        ParseArticle(article, out var personId, out var articleId);
        if (personId <= 0 || articleId <= 0) RedirectToAction(nameof(Blocked));
        var articleInDb = await db.Articles.SingleOrDefaultAsync(x => x.PersonId == personId && x.ArticleId == articleId) ?? throw new EntityNotFoundException();

        articleInDb.BlockedUsername = null;
        articleInDb.BlockedUtc = null;
        await db.SaveChangesAsync();

        return RedirectToAction(nameof(Blocked));
    }

    private static void ParseArticle(string article, out int personId, out int articleId)
    {
        personId = 0;
        articleId = 0;
        var ids = article.Split('_', '-', 'ß').Where(x => int.TryParse(x, out _)).Select(int.Parse).ToList();
        if (ids.Count != 2) return;
        personId = ids[0];
        articleId = ids[1];
    }
}

src/Bazza/Controllers/AdminUsersController.cs
using System.Threading.Tasks;
using Bazza.ViewModels.AdminUsers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bazza.Controllers;

public class AdminUsersController : Controller
{
    [Authorize(Roles = Roles.CanManageAdmin), HttpGet("/admin/users")]
    public async Task<IActionResult> Users([FromServices] UsersViewModelFactory factory)
    {
        return View(await factory.Build());
    }

    [Authorize(Roles = Roles.CanManageAdmin), HttpGet("/admin/user")]
    public async Task<IActionResult> EditUser([FromServices] EditUserViewModelFactory factory, [FromQuery] string? username)
    {
        return View(await factory.Build(username));
    }

    [Authorize(Roles = Roles.CanManageAdmin), HttpPost("/admin/user")]
    public async Task<IActionResult> EditUser([FromServices] EditUserViewModelFactory factory, EditUserViewModel viewModel, [FromQuery] string? username)
    {
        await factory.Validate(ModelState, viewModel, username);
        if (!ModelState.IsValid) return View(viewModel);
        await factory.UpdateDatabase(viewModel, username);
        return RedirectToAction(nameof(Users));
    }

    [Authorize(Roles = Roles.CanManageAdmin), HttpGet("/admin/user/delete")]
    public async Task<IActionResult> DeleteUser([FromServices] DeleteUserViewModelFactory factory, [FromQuery] string username)
    {
        return View(await factory.Build(username));
    }

    [Authorize(Roles = Roles.CanManageAdmin), HttpPost("/admin/user/delete")]
    public async Task<IActionResult> DeleteUser([FromServices] DeleteUserViewModelFactory factory, DeleteUserViewModel viewModel)
    {
        if (!ModelState.IsValid) return View(viewModel);
        await factory.UpdateDatabase(viewModel);
        return RedirectToAction(nameof(Users));
    }
}

src/Bazza/Controllers/UserController.cs
using System.Security.Claims;
using System.Threading.Tasks;
using Bazza.Models.Database;
using Bazza.ViewModels.User;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bazza.Controllers;

public class UserController : Controller
{
    [AllowAnonymous, HttpGet("/user/logout")]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        return Redirect("~/");
    }

    [AllowAnonymous, HttpGet("/user/login")]
    public IActionResult Login()
    {
        if (User.Identity?.IsAuthenticated == true) return RedirectToAction(nameof(AdminController.Index), "Admin");
        return View(new LoginViewModel());
    }

    [AllowAnonymous, HttpPost("/user/login")]
    public async Task<IActionResult> Login([FromServices] LoginViewModelFactory factory, [FromServices] Db db, LoginViewModel viewModel)
    {
        if (!ModelState.IsValid) return View(viewModel);
        viewModel = await factory.Login(viewModel);

        if (!viewModel.Error)
        {
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            var user = await db.Users.SingleAsync(x => x.Username.ToLower() == viewModel.Username.ToLower());
            if (user.CanManageAdmin) identity.AddClaim(new Claim(ClaimTypes.Role, Roles.CanManageAdmin));
            if (user.CanManagePersons) identity.AddClaim(new Claim(ClaimTypes.Role, Roles.CanManagePersons));
            if (user.CanManageSales) identity.AddClaim(new Claim(ClaimTypes.Role, Roles.CanManageSales));
            identity.AddClaim(new Claim(ClaimTypes.Name, viewModel.Username));
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));

            if (viewModel.RequiresPasswordReset)
                return RedirectToAction(nameof(ResetPassword), new
                {
                    username = viewModel.Username
                });
            return RedirectToAction(nameof(AdminController.Index), "Admin");
        }

        return View(viewModel);
    }

    [AllowAnonymous, HttpGet("/user/reset-password")]
    public async Task<IActionResult> ResetPassword([FromServices] ResetPasswordViewModelFactory factory, ResetPasswordViewModel viewModel)
    {
        viewModel = await factory.FillReadonly(viewModel);
        return View(viewModel);
    }

    [AllowAnonymous, HttpPost("/user/reset-password")]
    public async Task<IActionResult> HandleResetPassword([FromServices] ResetPasswordViewModelFactory factory, ResetPasswordViewModel viewModel)
    {
        if (!ModelState.IsValid) return View(nameof(ResetPassword), viewModel);
        viewModel = await factory.ResetPassword(viewModel);
        return View(nameof(ResetPassword), viewModel);
    }
}

src/Bazza/Views/Shared/_Layout.cshtml
@using System.Globalization
@using System.Reflection
@{ var version = typeof(Startup).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion; }

<!DOCTYPE html>
<html lang="@CultureInfo.CurrentUICulture.TwoLetterISOLanguageName">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Basar Neufelden</title>

    <script defer data-domain="basar.neufelden.at" src="https://plausible.io/js/plausible.js"></script>

    @* ReSharper disable once Html.PathError *@
    <link rel="stylesheet" href="~/css/bundle.css?v=@version"/>
</head>
<body>

<partial name="_Navigation" />

<main class="container" style="padding-left:.5rem; padding-right: .5rem;">
    @RenderBody()
</main>

<footer class="footer container">
    <div class="content has-text-centered">
        <p>
            Bei Fragen oder Schwierigkeiten bitte an @Settings.PrimaryResponsibleName unter <a href="mailto:@Settings.PrimaryResponsibleEmail">@Settings.PrimaryResponsibleEmail</a>
            oder <a href="tel:@Settings.PrimaryResponsiblePhone.NormalizePhoneNumber()">@Settings.PrimaryResponsiblePhone</a> wenden.<br/>
            v@(version) &copy; <a href="https://github.com/saxx/bazza">Hannes Sachsenhofer</a>
        </p>
    </div>
</footer>

@* ReSharper disable once Html.PathError *@
<script src="~/js/bundle.js?v=@version"></script>

@await RenderSectionAsync("Scripts", false)
</body>
</html>
<!-- Bazza v@(version) -->

src/Bazza/Views/Shared/_Navigation.cshtml
@if (User.Identity?.IsAuthenticated == true)
{
    <nav class="navbar is-fixed-top has-shadow" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <a asp-action="@nameof(AdminController.Index)" asp-controller="Admin" class="navbar-item">
                    Dashboard
                </a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbar" class="navbar-menu">
                <div class="navbar-start">

                    @if (User.IsInRole(Roles.CanManagePersons))
                    {
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link">
                                Registrierungen
                            </a>
                            <div class="navbar-dropdown">
                                <a asp-action="@nameof(AdminPersonsController.Persons)" asp-controller="AdminPersons" class="navbar-item">
                                    Übersicht
                                </a>
                                <a asp-action="@nameof(AdminPersonsController.PersonsStatistics)" asp-controller="AdminPersons" class="navbar-item">
                                    Statistiken
                                </a>
                            </div>
                        </div>
                    }

                    @if (User.IsInRole(Roles.CanManageSales))
                    {
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link">
                                Verkäufe
                            </a>
                            <div class="navbar-dropdown">
                                <a asp-action="@nameof(AdminSalesController.Sales)" asp-controller="AdminSales" class="navbar-item">
                                    Übersicht
                                </a>
                                <a asp-action="@nameof(AdminSalesController.Blocked)" asp-controller="AdminSales" class="navbar-item">
                                    Gesperrte Artikel
                                </a>
                                <a asp-action="@nameof(AdminSalesController.SalesStatistics)" asp-controller="AdminSales" class="navbar-item">
                                    Statistiken
                                </a>
                            </div>
                        </div>
                    }

                    @if (User.IsInRole(Roles.CanManageAdmin))
                    {
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link">
                                Administration
                            </a>
                            <div class="navbar-dropdown">
                                <a asp-action="@nameof(AdminUsersController.Users)" asp-controller="AdminUsers" class="navbar-item">
                                    Benutzer
                                </a>
                                <a asp-action="@nameof(AdminController.Settings)" asp-controller="Admin" class="navbar-item">
                                    Einstellungen
                                </a>
                                <a asp-action="@nameof(AdminController.ClearData)" asp-controller="Admin" class="navbar-item">
                                    Daten löschen
                                </a>
                                <a href="~/admin/hangfire" class="navbar-item">
                                    Hintergrundjobs
                                </a>
                            </div>
                        </div>
                    }
                </div>

                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            <a asp-action="@nameof(UserController.Logout)" asp-controller="User" class="button is-light">
                                Ausloggen
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
}